# Generated by Django 3.2 on 2021-04-27 18:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5999)])),
                ('object_class', models.CharField(choices=[('SF', 'Safe'), ('EC', 'Euclid'), ('KT', 'Keter'), ('TM', 'Thaumiel'), ('NT', 'Neutralized'), ('EP', 'Explained'), ('EO', 'Esoteric/Narrative'), ('DC', 'Decommissioned')], default='SF', max_length=18)),
                ('containment_procedures', models.TextField()),
                ('description', models.TextField()),
                ('additional', models.TextField()),
            ],
        ),
    ]
