# Generated by Django 3.0.5 on 2021-04-27 19:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scp_series', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='object',
            name='item',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(5999)]),
        ),
        migrations.AlterField(
            model_name='object',
            name='object_class',
            field=models.CharField(choices=[('Safe', 'Safe'), ('Euclid', 'Euclid'), ('Keter', 'Keter'), ('Thaumiel', 'Thaumiel'), ('Neutralized', 'Neutralized'), ('Explained', 'Explained'), ('Esoteric/Narrative', 'Esoteric/Narrative'), ('Decommissioned', 'Decommissioned')], default='SF', max_length=18),
        ),
    ]
