# Generated by Django 3.0.5 on 2021-04-27 20:26

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scp_series', '0002_auto_20210427_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='item'),
        ),
    ]
